//Login request
POST http://localhost:8080/account/login
Content-Type: application/json

{
    "name": "felix",
    "password": "test"
}
###

/// Register new user
POST http://localhost:8080/account/register
Content-Type: application/json

{
    "username": "felix",
    "email": "testgmail",
    "password": "test"
}
###

GET http://localhost:8080/account/user
Content-Type: application/json


###
DELETE http://localhost:8080/account/logout
Content-Type: application/json

###
GET http://localhost:8080/posts
Content-Type: application/json
###

DELETE http://localhost:8080/post/6269085c3d07e999f28179f4
Content-Type: application/json