GET http://localhost:8080/test

###

//Login request
POST http://localhost:8080/login
Content-Type: application/json

{
    "name": "test",
    "password": "test"
}
###

//Hämtar alla användare
GET http://localhost:8080/users
###

// Ny användare
POST http://localhost:8080/register
###


//Lägger till ny user
POST http://localhost:8080/user
####

//Tar bort user
DELETE http://localhost:8080/user
###

//Hämtar alla posts
GET http://localhost:8080/posts
###

//Lägger till post
POST http://localhost:8080/post
###

//Tar bort post
DELETE http://localhost:8080/post
###

//Hämtar inloggade användaren
GET http://localhost:8080/login


