//Login request
POST http://localhost:8080/account/login
Content-Type: application/json

{
    "name": "adam",
    "password": "test"
}
###

/// Register new user
POST http://localhost:8080/account/register
Content-Type: application/json

{
    "username": "belle",
    "email": "belle@ferrari.com",
    "password": "test"
}
###

GET http://localhost:8080/account/user
Content-Type: application/json


###
DELETE http://localhost:8080/account/logout
Content-Type: application/json

###
GET http://localhost:8080/posts
Content-Type: application/json
###


// Ta bort en post
DELETE http://localhost:8080/post/6267b33247949a8db72a09bf
Content-Type: application/json

###
POST http://localhost:8080/post
Content-Type: application/json

{
    "title": "hejhej",
    "content": "wagwan"
}

### 
PUT http://localhost:8080/post/626a8e8f9d74580c6da09696
Content-Type: application/json

{
    "title": "redigerar",
    "content": "redigerar"
}